#include <stdio.h>
#include "sentences/_HEADERS.h"

// I assume all of you know C.

int main( void )
{
    printf("\n");
    bensSentence1();
    printf("\n\n");

    // Add your sentence.
    // Don't forget to update the header file.
    // vvvvvvvvvvvvvvvv STUDENT WORK H
	snhqm9_sentence1();
    jtl378_sentence1();
    shensSentence1();
    //dw8b9First();
    snhqm9_sentence1();
    jtl378_sentence1();
    shensSentence1();
    ampvy7Sentence1();
    lch3m4Sentence1();
    //ampvy7Sentence1();
    dwdb79_sentence1();
    jtl378_sentence2();
    cgj6hb_sentence1();
    cdw8b9Second();
    mdsf3fSentence1();
	bcspq4sent1();
	bcspq4sent2();
	//ampvy7Sentence2();
    pje279Sentence1();
    rml3mdFirstSentence();
    ajpt33First();
    nicolasSmithsSentence1();
    acmyfFirst();
    mtrmt9First();
    crm4g3First();
    jarpqdSentence1();
    yqzn9_one();
    blkz85First();
    printf("\n\n");
    jmpcz9NewSentence1();
	kfjmbb_sentence2();
	xwq58First();
    printf("\n\n");
    jmpcz9NewSentence1();
    kjf3mdSentence1();
	kfjmbb_sentence2();
    ams938sentence1();
    cjm539sent1();
	crm4g3Second();
	colejcsent1();
    yzghf();
    jdckw4_sentence1();
    mattDSent2();
    cjan8cSentenceTwo();
	kfjmbb_sentence1();
    printf("\n\n");
    szz63one();
    hagd5dSentence1();
    cjan8cSentenceOne();
    sskgz8sentence1();
    mtrmt9Second();
    jah3xc_sentence1();
    klft2();
    mkc42Sentence1();
    jdckw4_sentence2();
    jarpqdSentence2();
    scfpt6Sentence1();
    jg229Sentence1();
    snhqm9_sentence2();
    rml3mdSecondSentence();
    cgj6hb_sentence2();
    pje279Sentence2();
    nicolasSmithsSentence2();
    mdsf3fSentence2();
    jah3xc_sentence2();
    casty8Sentence1();
    shensSentence_FINAL();
    acmyfSecond();
    jmpcz9NewSentence2();
    ajpt33Second();
    yzghf2();
    cjm539sent2();
	colejcsent2();
    sskgz8sentence_FINAL();
    szz63two();
    hagd5dSentence2();
    ob44fFirstSentence();
    klft2_1();
    jg229Sentence2();
    casty8Sentence2();
    ajt3m8_sentence1();
    mkc42Sentence2();
    scfpt6Sentence2();
    nicksen2();
    printf("\n\n");
    med43bSentence();
    nicksen1();
    med43bSentence2();
    yqzn9_two();
    mattDSent1();
    ob44fSecondSentence();
    rhhq7Sentence1();
    rhhq7Sentence2();
    blkz85Second();
    ncsgg7_sentence1();
    twv8f9Sentence1();
    agom94Sentence1();

	printf("\n\n");
    agom94Sentence2();
    rrsqp4sentence1();
    printf("\n\n");
    med43bSentence();
    nicksen1();
    mmjfz9sentence2();
    med43bSentence2();
    yqzn9_two();
    mattDSent1();
    dwdb79_sentence2();
    ams938sentence2();
    kjf3mdSentence_FINAL();
    ob44fSecondSentence();
    rhhq7Sentence1();
    rhhq7Sentence2();
    mmjfz9sentence1();
    zanSentenceOne();
    basqr4Sentence1();
    zanSentenceTwo();
    basqr4Sentence2();
    annhx3Sentence1();
    annhx3Sentence2();
    aupkbdsentence1();
    rrsqp4sentence2();
    aupkbdsentence2();
    xwq58Second();
    twv8f9Sentence2();
    lch3m4Sentence2();
	asbrm5Sentence1();
	asbrm5Sentence2();
    SkySentenceOne();
    SkySentenceTwo();
	rmmpfbSentence1();
	rmmpfbSentence2();
	apsrz4First();
	apsrz4Second();
    ajt3m8_sentence2();
    bdfhdcFirstSentence();
    bdfhdcSecondSentence();
    ncsgg7_sentence2();
    //bdfhdcFirstSentence();
    //bdfhdcSecondSentence();

    xlwbcSentence1();
    xlwbcSentence_FINAL();
    // DO NOT ADD AFTER THIS COMMENT
    // Bens sentence should be last.
}

